### PR TITLE
Add Initial Saswell T29UTW-7-Wifi support

### PR DESCRIPTION
**Pull request by radredgreen**
Hi Paul,

I've used your code base as a starting point to add support for a T29UTW-7-WIFI thermostat.  Unfortunately the module comes with a WR4 wifi module, so I had to replace it with a ESP8266 based module.  

Would you consider merging a pull request like this?

Thanks,
Radredgreen

### CODE REVIEW

**Comment by paullj1** [comment]
@radredgreen,

This is awesome!  I'm torn on merging it though.  It's outside the scope of the project, but I can just re-name the repo/project to be something like "Tuya-HomeKit," but I don't want to confuse people.  What do you think?

-Paul

**Comment by radredgreen** [comment]
Hi Paul,

I think that's a good idea, but entirely up to you.  I also like the Tuya-Homekit project name.  I saw your post on @ravensystem's esp-homekit-devices project which is how I found this.  I'd like to find a way to incorporate this functionality in his project and make it programmable by config file, but I'm not sure how to implement this amount of logic in his code base - especially given the binary size constraints on that project.

-Radredgreen

**Comment by paullj1** [comment]
Thanks for the contribution!  I'm definitely going to expand the scope of the repo, and add some docs for your device.

**Comment by radredgreen** [comment]
That's great news.  I've converted 3 thermostats now and they've been working great for about a month.  I have been using ESP01 modules and have had good success.  I've got a few photos of soldering the wires to the board and a picture of the corner of the case that I tucked the ESP01 module - let me know if you'd like those for the docs.

**Pull request merged**
